LoveLetter_platform_index:
    path:     /index
    defaults: { _controller: LoveLetterPlatformBundle:Advert:index }
    
LoveLetter_platform_accueil:
    path: /accueil
    defaults: 
        _controller: LoveLetterPlatformBundle:Home:Accueil 

LoveLetter_platform_AffichageJeu:
    path: /Partie
    defaults: 
        _controller: LoveLetterPlatformBundle:Partie:AffichageJeu

LoveLetter_platform_initialisation:
    path: /Initialisation
    defaults: 
        _controller: LoveLetterPlatformBundle:Carte:RemplisageTableCarte
        
LoveLetter_platform_UtilisateurCreerPartie:
    path: /UtilisateurCreerPartie
    defaults: 
        _controller: LoveLetterPlatformBundle:Partie:UtilisateurCreerPartie
        
LoveLetter_platform_UtilisateurRejoinsPartie:
    path: /UtilisateurRejoinsPartie
    defaults: 
        _controller: LoveLetterPlatformBundle:Partie:UtilisateurRejoinsPartie
      
LoveLetter_platform_CreationPartie:
    path: /LancementPartie/{nom}
    defaults:
           _controller: LoveLetterPlatformBundle:Partie:CreationPartie
           
LoveLetter_platform_DebutManche:
    path: /DebutManche
    defaults:
           _controller: LoveLetterPlatformBundle:Partie:DebutManche
           
LoveLetter_platform_DistributionCarte:
    path: /DistributionCarte
    defaults:
           _controller: LoveLetterPlatformBundle:Partie:DistributionCarte
           
LoveLetter_platform_TirerCarte:
    path: /TirerCarte
    defaults:
           _controller: LoveLetterPlatformBundle:Partie:TirerCarte
           
LoveLetter_platform_Choix:
    path: /Choix
    defaults:
           _controller: LoveLetterPlatformBundle:Carte:Choix

LoveLetter_platform_Garde:
    path: /Garde
    defaults:
           _controller: LoveLetterPlatformBundle:Carte:Garde
           
LoveLetter_platform_GardeChoix:
    path: /GardeChoix
    defaults:
           _controller: LoveLetterPlatformBundle:Carte:GardeChoix
           
LoveLetter_platform_Pretre:
    path: /Pretre
    defaults:
           _controller: LoveLetterPlatformBundle:Carte:Pretre

LoveLetter_platform_Baron:
    path: /Baron
    defaults:
           _controller: LoveLetterPlatformBundle:Carte:Baron

LoveLetter_platform_Servante:
    path: /Servante
    defaults:
           _controller: LoveLetterPlatformBundle:Carte:Servante

LoveLetter_platform_Prince:
    path: /Prince
    defaults:
           _controller: LoveLetterPlatformBundle:Carte:Prince

LoveLetter_platform_PrinceChoix:
    path: /PrinceChoix
    defaults:
           _controller: LoveLetterPlatformBundle:Carte:PrinceChoix

LoveLetter_platform_Roi:
    path: /Roi
    defaults:
           _controller: LoveLetterPlatformBundle:Carte:Roi
           
LoveLetter_platform_RoiChoix:
    path: /RoiChoix
    defaults:
           _controller: LoveLetterPlatformBundle:Carte:RoiChoix

LoveLetter_platform_Comtesse:
    path: /Comtesse
    defaults:
           _controller: LoveLetterPlatformBundle:Carte:Comtesse

LoveLetter_platform_Princesse:
    path: /Princesse
    defaults:
           _controller: LoveLetterPlatformBundle:Carte:Princesse
           
LoveLetter_platform_TestFin:
    path: /TestFin
    defaults:
           _controller: LoveLetterPlatformBundle:Partie:TestFin
