LoveLetter_platform_index:
    path:     /index
    defaults: { _controller: LoveLetterPlatformBundle:Advert:index }
    
LoveLetter_platform_accueil:
    path: /accueil
    defaults: 
        _controller: LoveLetterPlatformBundle:Home:Accueil 
        
LoveLetter_platform_add:
    path: /add
    defaults: 
        _controller: LoveLetterPlatformBundle:Home:add
        
LoveLetter_platform_CreationPartie:
    path: /CreationPartie
    defaults: 
        _controller: LoveLetterPlatformBundle:Home:CreationPartie
        
LoveLetter_platform_ChercheManche:
    path: /ChercheManche/{id}
    defaults: 
        _controller: LoveLetterPlatformBundle:Home:ChercheManche
        
LoveLetter_platform_AffichageJeu:
    path: /Partie
    defaults: 
        _controller: LoveLetterPlatformBundle:Partie:AffichageJeu

LoveLetter_platform_initialisation:
    path: /Initialisation
    defaults: 
        _controller: LoveLetterPlatformBundle:Carte:RemplisageTableCarte
        
LoveLetter_platform_UtilisateurCreerPartie:
    path: /UtilisateurCreerPartie
    defaults: 
        _controller: LoveLetterPlatformBundle:Partie:UtilisateurCreerPartie
        
LoveLetter_platform_UtilisateurRejoinsPartie:
    path: /UtilisateurRejoinsPartie
    defaults: 
        _controller: LoveLetterPlatformBundle:Partie:UtilisateurRejoinsPartie
    
LoveLetter_platform_LancementPartie:
    path: /LancementPartie/{nom}/{nb}
    defaults:
           _controller: LoveLetterPlatformBundle:Partie:CreationPartie
    requirements:
        nb:   2|3|4
        
LoveLetter_platform_DebutManche:
    path: /DebutManche
    defaults:
           _controller: LoveLetterPlatformBundle:Partie:DebutManche
           
LoveLetter_platform_DistributionCarte:
    path: /DistributionCarte
    defaults:
           _controller: LoveLetterPlatformBundle:Partie:DistributionCarte
           
LoveLetter_platform_TirerCarte:
    path: /TirerCarte
    defaults:
           _controller: LoveLetterPlatformBundle:Partie:TirerCarte
           
LoveLetter_platform_Choix:
    path: /Choix
    defaults:
           _controller: LoveLetterPlatformBundle:Carte:Choix

LoveLetter_platform_GardeChoix:
    path: /GardeChoix
    defaults:
           _controller: LoveLetterPlatformBundle:Carte:GardeChoix

LoveLetter_platform_GardeChoix2:
    path: /GardeChoix2
    defaults:
           _controller: LoveLetterPlatformBundle:Carte:GardeChoix2

           
LoveLetter_platform_PretreChoix:
    path: /PretreChoix
    defaults:
           _controller: LoveLetterPlatformBundle:Carte:PretreChoix

           
LoveLetter_platform_BaronChoix:
    path: /BaronChoix
    defaults:
           _controller: LoveLetterPlatformBundle:Carte:BaronChoix

LoveLetter_platform_PrinceChoix:
    path: /PrinceChoix
    defaults:
           _controller: LoveLetterPlatformBundle:Carte:PrinceChoix

LoveLetter_platform_RoiChoix:
    path: /RoiChoix
    defaults:
           _controller: LoveLetterPlatformBundle:Carte:RoiChoix
           
LoveLetter_platform_TestFin:
    path: /TestFin
    defaults:
           _controller: LoveLetterPlatformBundle:Partie:TestFin
