LoveLetter_platform_index:
    path:     /index
    defaults: { _controller: LoveLetterPlatformBundle:Advert:index }
    
LoveLetter_platform_accueil:
    path: /accueil
    defaults: 
        _controller: LoveLetterPlatformBundle:Home:Accueil 

        
LoveLetter_platform_AffichageJeu:
    path: /Partie
    defaults: 
        _controller: LoveLetterPlatformBundle:Partie:AffichageJeu

LoveLetter_platform_initialisation:
    path: /Initialisation
    defaults: 
        _controller: LoveLetterPlatformBundle:Partie:RemplisageTableCarte
        
LoveLetter_platform_UtilisateurCreerPartie:
    path: /UtilisateurCreerPartie
    defaults: 
        _controller: LoveLetterPlatformBundle:Partie:UtilisateurCreerPartie
        
LoveLetter_platform_UtilisateurRejoinsPartie:
    path: /UtilisateurRejoinsPartie
    defaults: 
        _controller: LoveLetterPlatformBundle:Partie:UtilisateurRejoinsPartie
      
LoveLetter_platform_CreationPartie:
    path: /LancementPartie/{nom}
    defaults:
           _controller: LoveLetterPlatformBundle:Partie:CreationPartie
           
LoveLetter_platform_DebutManche:
    path: /DebutManche
    defaults:
           _controller: LoveLetterPlatformBundle:Partie:DebutManche
           
LoveLetter_platform_DistributionCarte:
    path: /DistributionCarte
    defaults:
           _controller: LoveLetterPlatformBundle:Partie:DistributionCarte
           
LoveLetter_platform_TirerCarte:
    path: /TirerCarte
    defaults:
           _controller: LoveLetterPlatformBundle:Partie:TirerCarte
           
LoveLetter_platform_Choix:
    path: /Choix
    defaults:
           _controller: LoveLetterPlatformBundle:Partie:Choix
