parameters:
#    love_letter_platform.example.class: LoveLetter\PlatformBundle\Example

services:
#    love_letter_platform.example:
#        class: %love_letter_platform.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
